In [37]:
import pandas as pd
import numpy as np
import scipy as sp
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as py
import statsmodels as sm
from scipy import stats

In [29]:
df = pd.read_csv("Clean_Dataset.csv")
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [30]:
df.isna().sum()

Unnamed: 0          0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

## DESCRITE VARIABLES 
1 . Airline

2 . Fight

3 . source_city

4 . departure_time

5 . stops

6 . arrival_time

7 . destination_city

8 . class 

9 . days_left

## CONTINOUS VARIABLES 

1 . duration 

2 . price

## 3️⃣ Analyse univariée

## TESTS

#### H0 : Airline has no effect on price

In [ ]:
# Airline vs Price
groups = [group["price"].values for _, group in df.groupby("airline")]
res = stats.f_oneway(*groups)
p_value = res.pvalue

alpha = 0.05
print(f"p-value: {p_value}")
if p_value < alpha:
    print("Reject H0 → airline significantly affects price ")
else:
    print("Fail to reject H0 → no significant effect ")

p-value: 0.0
Reject H0 → airline significantly affects price ✅

# Anova test
source_city gouped with destination_city vs price

In [34]:
#source_des =  df.groupby([df["source_city"], df["destination_city"]])

groups = [group["price"].values 
        for _, group in df.groupby(["source_city", "destination_city"])]
res = stats.f_oneway(*groups)
p_value = res.pvalue
alpha = 0.05
print(f"p-value: {p_value:.3f}")
if p_value < alpha:
    print("Reject H0 → route significantly affects price ")
else:
    print("Fail to reject H0 → no significant effect ")

p-value: 0.000
Reject H0 → route significantly affects price

In [42]:
airlines = df["airline"].unique().tolist()
dict_airline_prices = {}
for airline in airlines :
    airline_prices = df[df['airline'] == airline]['price']
    dict_airline_prices[airline] = airline_prices

anova_results = sp.stats.f_oneway(*dict_airline_prices.values())
print(f"P-value:{anova_results[1]:.10f}")

P-value:0.0000000000